services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rsflow
    ports:
      - "5433:5432"
    volumes:
      - rsflow_postgres_data:/var/lib/postgresql/data

volumes:
  rsflow_postgres_data:
